//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topshelf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Topshelf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot execute stage: &apos;{0}&apos;..
        /// </summary>
        internal static string CantExecuteStage {
            get {
                return ResourceManager.GetString("CantExecuteStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot register service file &apos;{0}&apos;: &apos;{1}&apos;..
        /// </summary>
        internal static string CantRegisterServiceFile {
            get {
                return ResourceManager.GetString("CantRegisterServiceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve file status: &apos;{0}&apos;..
        /// </summary>
        internal static string CantRetrieveFileStatus {
            get {
                return ResourceManager.GetString("CantRetrieveFileStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot rollback stage: &apos;{0}&apos;..
        /// </summary>
        internal static string CantRollbackStage {
            get {
                return ResourceManager.GetString("CantRollbackStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set file as executable: &apos;{0}&apos;..
        /// </summary>
        internal static string CantSetFileAsExecutable {
            get {
                return ResourceManager.GetString("CantSetFileAsExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start service &apos;{0}&apos;: &apos;{1}&apos;..
        /// </summary>
        internal static string CantStartService {
            get {
                return ResourceManager.GetString("CantStartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot stop service &apos;{0}&apos;: &apos;{1}&apos;..
        /// </summary>
        internal static string CantStopService {
            get {
                return ResourceManager.GetString("CantStopService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot unregister service file &apos;{0}&apos;: &apos;{1}&apos;..
        /// </summary>
        internal static string CantUnregisterServiceFile {
            get {
                return ResourceManager.GetString("CantUnregisterServiceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating service file.
        /// </summary>
        internal static string CreateServiceFileStage {
            get {
                return ResourceManager.GetString("CreateServiceFileStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing rollback transaction failed..
        /// </summary>
        internal static string ExecutingRollbackTransactionFailed {
            get {
                return ResourceManager.GetString("ExecutingRollbackTransactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing stage &apos;{0}&apos; is completed with errors: &apos;{1}&apos;..
        /// </summary>
        internal static string ExecutingStageIsCompletedWithErrors {
            get {
                return ResourceManager.GetString("ExecutingStageIsCompletedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing stage &apos;{0}&apos; is started..
        /// </summary>
        internal static string ExecutingStageIsStarted {
            get {
                return ResourceManager.GetString("ExecutingStageIsStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing stage &apos;{0}&apos; is successfully completed..
        /// </summary>
        internal static string ExecutingStageIsSuccessfullyCompleted {
            get {
                return ResourceManager.GetString("ExecutingStageIsSuccessfullyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing transaction failed..
        /// </summary>
        internal static string ExecutingTransactionFailed {
            get {
                return ResourceManager.GetString("ExecutingTransactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstallHostSettings were not defined..
        /// </summary>
        internal static string InstallHostSettingsWereNotDefined {
            get {
                return ResourceManager.GetString("InstallHostSettingsWereNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing service &apos;{0}&apos; is completed with errors..
        /// </summary>
        internal static string InstallingServiceFailed {
            get {
                return ResourceManager.GetString("InstallingServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing service &apos;{0}&apos; is completed with errors: &apos;{1}&apos;..
        /// </summary>
        internal static string InstallingServiceIsCompletedWithErrors {
            get {
                return ResourceManager.GetString("InstallingServiceIsCompletedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing service &apos;{0}&apos; is started..
        /// </summary>
        internal static string InstallingServiceIsStarted {
            get {
                return ResourceManager.GetString("InstallingServiceIsStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing service &apos;{0}&apos; is successfully completed..
        /// </summary>
        internal static string InstallingServiceIsSuccessfullyCompleted {
            get {
                return ResourceManager.GetString("InstallingServiceIsSuccessfullyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #! /bin/sh
        ///### BEGIN INIT INFO
        ///# Provides:          &lt;ServiceName&gt;
        ///# Required-Start:    &lt;Dependencies&gt;
        ///# Required-Stop:     &lt;Dependencies&gt;
        ///# Default-Start:     2 3 4 5
        ///# Default-Stop:      0 1 6
        ///# Short-Description: &lt;DisplayName&gt;
        ///# Description:       &lt;Description&gt;
        ///### END INIT INFO
        ///
        ///############### EDIT ME ##################
        ///MONO_PATH=$(which mono)
        ///MONO_ARGS=&quot;&quot;
        ///SERVICE_DIR=&quot;&lt;ServiceDir&gt;&quot;
        ///SERVICE_EXE=&quot;&lt;ServiceExe&gt;&quot;
        ///SERVICE_ARGS=&quot;&lt;ServiceArgs&gt;&quot;
        ///SERVICE_USER=&quot;&lt;ServiceUser&gt;&quot;
        ///SERVICE_PID_DIR=&quot;&lt;S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LinuxServiceScript {
            get {
                return ResourceManager.GetString("LinuxServiceScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering service file.
        /// </summary>
        internal static string RegisterServiceFileStage {
            get {
                return ResourceManager.GetString("RegisterServiceFileStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback stage &apos;{0}&apos; is completed with errors: &apos;{1}&apos;..
        /// </summary>
        internal static string RollbackStageIsCompletedWithErrors {
            get {
                return ResourceManager.GetString("RollbackStageIsCompletedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback stage &apos;{0}&apos; is started..
        /// </summary>
        internal static string RollbackStageIsStarted {
            get {
                return ResourceManager.GetString("RollbackStageIsStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback stage &apos;{0}&apos; is successfully completed..
        /// </summary>
        internal static string RollbackStageIsSuccessfullyCompleted {
            get {
                return ResourceManager.GetString("RollbackStageIsSuccessfullyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; did not start successfully (returned false)..
        /// </summary>
        internal static string ServiceDidntStartSuccessfully {
            get {
                return ResourceManager.GetString("ServiceDidntStartSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; did not stop successfully (returned false)..
        /// </summary>
        internal static string ServiceDidntStopSuccessfully {
            get {
                return ResourceManager.GetString("ServiceDidntStopSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; has not installed..
        /// </summary>
        internal static string ServiceHasntInstalled {
            get {
                return ResourceManager.GetString("ServiceHasntInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service must be executable file..
        /// </summary>
        internal static string ServiceMustBeExecutableFile {
            get {
                return ResourceManager.GetString("ServiceMustBeExecutableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; started..
        /// </summary>
        internal static string ServiceStarted {
            get {
                return ResourceManager.GetString("ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; stopped..
        /// </summary>
        internal static string ServiceStopped {
            get {
                return ResourceManager.GetString("ServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop requested by hosted service: &apos;{0}&apos;..
        /// </summary>
        internal static string ServiceStopRequested {
            get {
                return ResourceManager.GetString("ServiceStopRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set service file as executable.
        /// </summary>
        internal static string SetServiceFileAsExecutableStage {
            get {
                return ResourceManager.GetString("SetServiceFileAsExecutableStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting service: &apos;{0}&apos;..
        /// </summary>
        internal static string StartingService {
            get {
                return ResourceManager.GetString("StartingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; did not start successfully..
        /// </summary>
        internal static string StartServiceFailed {
            get {
                return ResourceManager.GetString("StartServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping service: &apos;{0}&apos;..
        /// </summary>
        internal static string StoppingService {
            get {
                return ResourceManager.GetString("StoppingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; did not stop successfully..
        /// </summary>
        internal static string StopServiceFailed {
            get {
                return ResourceManager.GetString("StopServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service threw an unhandled exception: &apos;{0}&apos;..
        /// </summary>
        internal static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling service &apos;{0}&apos; is completed with errors..
        /// </summary>
        internal static string UninstallingServiceFailed {
            get {
                return ResourceManager.GetString("UninstallingServiceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling service &apos;{0}&apos; is completed with errors: &apos;{1}&apos;..
        /// </summary>
        internal static string UninstallingServiceIsCompletedWithErrors {
            get {
                return ResourceManager.GetString("UninstallingServiceIsCompletedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling service &apos;{0}&apos; is started..
        /// </summary>
        internal static string UninstallingServiceIsStarted {
            get {
                return ResourceManager.GetString("UninstallingServiceIsStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling service &apos;{0}&apos; is successfully completed..
        /// </summary>
        internal static string UninstallingServiceIsSuccessfullyCompleted {
            get {
                return ResourceManager.GetString("UninstallingServiceIsSuccessfullyCompleted", resourceCulture);
            }
        }
    }
}
